# Generated by Django 4.0.5 on 2022-07-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_rename_randomtest_testusers_delete_randomtest2'),
    ]

    operations = [
        migrations.AddField(
            model_name='testusers',
            name='occupation',
            field=models.CharField(default='default', max_length=128),
        ),
    ]
